FROM python:3.11-slim
WORKDIR /app
COPY requirements-transform-gold.txt .
RUN pip install --no-cache-dir -r requirements-transform-gold.txt
COPY src/medallion/gold/ ./src/medallion/gold/
CMD ["python", "src/medallion/gold/transform_gold.py"]